!****	DAKAH.CTL
@DEFINE DSK DSK:,<KIRCHOFF>
!*****	ASSEMBLE PROGRAM
MAC::@R MACRO
*DAKAH@
@IF (ERROR) @GOTO BLO
LNK::@R LINK
*DAKAH.SAV/SAV=DAKAH/NOSYM/NOINIT/GO
@IF (ERROR) @GOTO BLO
CRF::@R CREF
*DSK:DAKAH.LST_DAKAH
@IF (ERROR) @GOTO BLO
DC2::@RUN DECDOC.SAV
*DAKAH/S=DAKAH.TXT,DAKAH.HST,DAKAH.LST
@IF (ERROR) @GOTO BLO
DEL::@DEL DAKAH.LST,DAKAH.REL
@IF (ERROR) @GOTO BLO
@GOTO LOG
!
BLO::@R PIP
*DAKAH.BLO=NUL:FOO
LOG::
