!****	DAKBA.CTL
@DEFINE DSK DSK:,<KIRCHOFF>
!*****	ASSEMBLE PROGRAM
MAC::@R MACRO
*DAKBA@
@IF (ERROR) @GOTO BLO
LNK::@R LINK
*DAKBA.SAV/SAV=DAKBA/NOSYM/NOINIT/GO
@IF (ERROR) @GOTO BLO
CRF::@R CREF
*DSK:DAKBA.LST_DAKBA
@IF (ERROR) @GOTO BLO
DC2::@RUN DECDOC.SAV
*DAKBA/S=DAKBA.TXT,DAKBA.HST,DAKBA.LST
@IF (ERROR) @GOTO BLO
DEL::@DEL DAKBA.LST,DAKBA.REL
@IF (ERROR) @GOTO BLO
@GOTO LOG
!
BLO::@R PIP
*DAKBA.BLO=NUL:FOO
LOG::
