!****	DAKBD.CTL
@DEFINE DSK DSK:,<KIRCHOFF>
!*****	ASSEMBLE PROGRAM
MAC::@R MACRO
*DAKBD@
@IF (ERROR) @GOTO BLO
LNK::@R LINK
*DAKBD.SAV/SAV=DAKBD/NOSYM/NOINIT/GO
@IF (ERROR) @GOTO BLO
CRF::@R CREF
*DSK:DAKBD.LST_DAKBD
@IF (ERROR) @GOTO BLO
DC2::@RUN DECDOC.SAV
*DAKBD/S=DAKBD.TXT,DAKBD.HST,DAKBD.LST
@IF (ERROR) @GOTO BLO
DEL::@DEL DAKBD.LST,DAKBD.REL
@IF (ERROR) @GOTO BLO
@GOTO LOG
!
BLO::@R PIP
*DAKBD.BLO=NUL:FOO
LOG::
