!****	DAKBB.CTL
@DEFINE DSK DSK:,<KIRCHOFF>
!*****	ASSEMBLE PROGRAM
MAC::@R MACRO
*DAKBB@
@IF (ERROR) @GOTO BLO
LNK::@R LINK
*DAKBB.SAV/SAV=DAKBB/NOSYM/NOINIT/GO
@IF (ERROR) @GOTO BLO
CRF::@R CREF
*DSK:DAKBB.LST_DAKBB
@IF (ERROR) @GOTO BLO
DC2::@RUN DECDOC.SAV
*DAKBB/S=DAKBB.TXT,DAKBB.HST,DAKBB.LST
@IF (ERROR) @GOTO BLO
DEL::@DEL DAKBB.LST,DAKBB.REL
@IF (ERROR) @GOTO BLO
@GOTO LOG
!
BLO::@R PIP
*DAKBB.BLO=NUL:FOO
LOG::
