!****	DAKBC.CTL
@DEFINE DSK DSK:,<KIRCHOFF>
!*****	ASSEMBLE PROGRAM
MAC::@R MACRO
*DAKBC@
@IF (ERROR) @GOTO BLO
LNK::@R LINK
*DAKBC.SAV/SAV=DAKBC/NOSYM/NOINIT/GO
@IF (ERROR) @GOTO BLO
CRF::@R CREF
*DSK:DAKBC.LST_DAKBC
@IF (ERROR) @GOTO BLO
DC2::@RUN DECDOC.SAV
*DAKBC/S=DAKBC.TXT,DAKBC.HST,DAKBC.LST
@IF (ERROR) @GOTO BLO
DEL::@DEL DAKBC.LST,DAKBC.REL
@IF (ERROR) @GOTO BLO
@GOTO LOG
!
BLO::@R PIP
*DAKBC.BLO=NUL:FOO
LOG::
