!****	DAKDB.CTL
@DEFINE DSK DSK:,<KIRCHOFF>
!*****	ASSEMBLE PROGRAM
MAC::@R MACRO
*DAKDB@
@IF (ERROR) @GOTO BLO
LNK::@R LINK
*DAKDB.SAV/SAV=DAKDB/SYMSEG:LOW/LOCALS/GO
@IF (ERROR) @GOTO BLO
CRF::@R CREF
*DSK:DAKDB.LST_DAKDB
@IF (ERROR) @GOTO BLO
DC2::@RUN DECDOC.SAV
*DAKDB/S=DAKDB.TXT,DAKDB.HST,DAKDB.LST
@IF (ERROR) @GOTO BLO
DEL::@DEL DAKDB.LST,DAKDB.REL
@IF (ERROR) @GOTO BLO
@GOTO LOG
!
BLO::@R PIP
*DAKDB.BLO=NUL:FOO
LOG::
