!****	DAKDA.CTL
@DEFINE DSK DSK:,<KIRCHOFF>
!*****	ASSEMBLE PROGRAM
MAC::@R MACRO
*DAKDA@
@IF (ERROR) @GOTO BLO
LNK::@R LINK
*DAKDA.SAV/SAV=DAKDA/SYMSEG:LOW/LOCALS/GO
@IF (ERROR) @GOTO BLO
CRF::@R CREF
*DSK:DAKDA.LST_DAKDA
@IF (ERROR) @GOTO BLO
DC2::@RUN DECDOC.SAV
*DAKDA/S=DAKDA.TXT,DAKDA.HST,DAKDA.LST
@IF (ERROR) @GOTO BLO
DEL::@DEL DAKDA.LST,DAKDA.REL
@IF (ERROR) @GOTO BLO
@GOTO LOG
!
BLO::@R PIP
*DAKDA.BLO=NUL:FOO
LOG::
