!****	DSKCF.CTL	SEP-79
@MACRO
*@DSKCF
@IF (ERROR) @GOTO BLO
@RUN DLINK
*DSKCF.SAV/SAV=DSKCF/NOINIT/GO
@IF (ERROR) @GOTO BLO
@CREF
*DSKCF.LST=DSKCF
@IF (ERROR) @GOTO BLO
@RUN DECDOC
DSKCF
@IF (ERROR) @GOTO BLO
@RUN DECDOC
*DSKCF/S=DSKCF.TXT,DSKCF.HST,DSKCF.DOC,DSKCF.LST
@IF (ERROR) @GOTO BLO
BLO::
